import { describe, expect, test } from "bun:test"
import ConfigRepository from "@/config/repository"
import BuiltinContainer from "@/container/adapters/builtin"
import {
    DecryptError,
    EncryptError,
    Encrypter,
    EncryptionProvider,
    MissingAppKeyError,
    UnsupportedCipherError,
} from "@/encryption"
import ArchitectError from "@/errors/error"
import { DeferrableServiceProvider } from "@/support/service-provider"

// Generated by a verbatim port of Laravel 13's Encrypter::encryptString() in PHP/OpenSSL.
const laravel: Record<string, { key: string; payload: string }> = {
    "aes-128-cbc": {
        key: "base64:EBAQEBAQEBAQEBAQEBAQEA==",
        payload:
            "eyJpdiI6IlNaYStrVFIzZGttWWsxS2VJeWNvQUE9PSIsInZhbHVlIjoiTngxeWYzNTd2Uy82TWpXbzRPdlRWYUNEeFY2Z0JnNjB5QjlnMDU2cUh6RT0iLCJtYWMiOiJkZjQ3NDc0ODY4YzY0NTNlZjA3ZjBhY2JhN2ZlOTE1YThlMjRhZmZmYWU4NjI5MTA3MzAwMjI4NmFmMzhhYzJhIiwidGFnIjoiIn0=",
    },
    "aes-256-cbc": {
        key: "base64:ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA=",
        payload:
            "eyJpdiI6IlFrNmMwWjR6OUNCa2VpeGNTbXU3VEE9PSIsInZhbHVlIjoiWnovU3BFRXFSa1BJcjh3K1FIVnJMdFRENWhpYmlEa3NFeXREQWlOck9KVT0iLCJtYWMiOiIzYTQwMDI4M2EyYTljMzY2NmI5NDkwOGEzNzk1Y2MzYmFiZjE4ODk2NDI0Y2Q3OGE4N2Y0ZDYxZjA5MDA0MDg5IiwidGFnIjoiIn0=",
    },
    "aes-128-gcm": {
        key: "base64:EBAQEBAQEBAQEBAQEBAQEA==",
        payload:
            "eyJpdiI6IjZOeTdJUWRWRTQySnlWOW8iLCJ2YWx1ZSI6ImppYkV3dElobDZPNlZPTXp5amFzUFpSWTZ3PT0iLCJtYWMiOiIiLCJ0YWciOiJGSTJSUW9rV1VXNExNREJ6SFpYd1B3PT0ifQ==",
    },
    "aes-256-gcm": {
        key: "base64:ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA=",
        payload:
            "eyJpdiI6IkRQRDJmdUZ5Y0ZnSFVEVHUiLCJ2YWx1ZSI6Ikw3djdFb21VbE1RSEMrM2xFOUN1Zy85TTlBPT0iLCJtYWMiOiIiLCJ0YWciOiJPZGFuWnArR3V1QTUrU0w2NzhGd0tnPT0ifQ==",
    },
}

const PLAINTEXT = "héllo wörld / ✓"

const keyOf = (key: string) => Uint8Array.from(atob(key.slice("base64:".length)), (c) => c.charCodeAt(0))

const reencode = (payload: string, change: (data: Record<string, string>) => void) => {
    const data = JSON.parse(atob(payload))
    change(data)
    return btoa(JSON.stringify(data))
}

for (const [cipher, fixture] of Object.entries(laravel)) {
    describe(`Encrypter ${cipher}`, () => {
        const encrypter = () => new Encrypter(keyOf(fixture.key), cipher)

        test("decrypts a payload made by Laravel", async () => {
            expect(await encrypter().decryptString(fixture.payload)).toBe(PLAINTEXT)
        })

        test("produces Laravel's payload shape and round-trips", async () => {
            const payload = await encrypter().encryptString(PLAINTEXT)
            const data = JSON.parse(atob(payload))
            const aead = cipher.endsWith("gcm")

            expect(Object.keys(data)).toEqual(["iv", "value", "mac", "tag"])
            expect(data.mac).toMatch(aead ? /^$/ : /^[0-9a-f]{64}$/)
            expect(data.tag).toMatch(aead ? /^[A-Za-z0-9+/]{22}==$/ : /^$/)
            expect(payload).not.toBe(await encrypter().encryptString(PLAINTEXT))
            expect(await encrypter().decryptString(payload)).toBe(PLAINTEXT)
        })

        test("rejects tampered values, wrong keys, and malformed payloads with DecryptError", async () => {
            const tampered = reencode(fixture.payload, (data) => {
                data.value = `A${data.value.slice(1)}`
            })
            const other = new Encrypter(Encrypter.generateKey(cipher), cipher)

            for (const payload of [tampered, "not base64!", btoa("{}"), btoa("[1]")]) {
                await expect(encrypter().decryptString(payload)).rejects.toBeInstanceOf(DecryptError)
            }
            await expect(other.decryptString(fixture.payload)).rejects.toBeInstanceOf(DecryptError)
        })

        test("decrypts with a previous key after rotation", async () => {
            const rotated = new Encrypter(Encrypter.generateKey(cipher), cipher).previousKeys([keyOf(fixture.key)])
            expect(await rotated.decryptString(fixture.payload)).toBe(PLAINTEXT)
            expect(rotated.getAllKeys()).toHaveLength(2)
        })
    })
}

describe("Encrypter", () => {
    const key = Encrypter.generateKey("aes-128-cbc")

    test("encrypt() serializes values as JSON", async () => {
        const encrypter = new Encrypter(key)
        const value = { id: 42, tags: ["a", "b"], active: true }

        expect(await encrypter.decrypt(await encrypter.encrypt(value))).toEqual(value)
        expect(await encrypter.decryptString(await encrypter.encrypt("x"))).toBe('"x"')
    })

    test("encrypt() rejects values that can't be serialized", async () => {
        const error = await new Encrypter(key).encrypt(undefined).catch((e) => e)
        expect(error).toBeInstanceOf(EncryptError)
        expect(error).toBeInstanceOf(ArchitectError)
        expect(error.source).toBe("encryption")
    })

    test("reports the MAC failure Laravel reports", async () => {
        const encrypter = new Encrypter(key)
        const forged = reencode(await encrypter.encryptString("x"), (data) => {
            data.mac = "0".repeat(64)
        })
        await expect(encrypter.decryptString(forged)).rejects.toThrow("The MAC is invalid.")
    })

    test("rejects a tag on a CBC payload", async () => {
        const encrypter = new Encrypter(key)
        const tagged = reencode(await encrypter.encryptString("x"), (data) => {
            data.tag = btoa("x".repeat(16))
        })
        await expect(encrypter.decryptString(tagged)).rejects.toThrow("does not support AEAD")
    })

    test("defaults to aes-128-cbc", async () => {
        const payload = await new Encrypter(key).encryptString("x")
        expect(await new Encrypter(key, "aes-128-cbc").decryptString(payload)).toBe("x")
        expect(() => new Encrypter(Encrypter.generateKey("aes-256-cbc"))).toThrow(UnsupportedCipherError)
    })

    test("appearsEncrypted() recognizes the payload shape without decrypting", async () => {
        expect(Encrypter.appearsEncrypted(await new Encrypter(key).encryptString("x"))).toBe(true)
        expect(Encrypter.appearsEncrypted(laravel["aes-256-gcm"].payload)).toBe(true)
        expect(Encrypter.appearsEncrypted(btoa(JSON.stringify({ iv: "", value: "", mac: "" })))).toBe(true)
        expect(Encrypter.appearsEncrypted(btoa(JSON.stringify({ iv: "", value: "" })))).toBe(false)
        expect(Encrypter.appearsEncrypted("plain text")).toBe(false)
        expect(Encrypter.appearsEncrypted(btoa("null"))).toBe(false)
        expect(Encrypter.appearsEncrypted(42)).toBe(false)
    })

    test("unsupported ciphers and wrong key lengths throw UnsupportedCipherError", () => {
        expect(() => new Encrypter(key, "aes-256-ecb")).toThrow(UnsupportedCipherError)
        expect(() => new Encrypter(Encrypter.generateKey("aes-256-cbc"))).toThrow(UnsupportedCipherError)
        expect(() => new Encrypter(key).previousKeys([new Uint8Array(3)])).toThrow(UnsupportedCipherError)
        expect(Encrypter.supported(key, "AES-128-CBC")).toBe(true)
        expect(Encrypter.generateKey("aes-128-gcm")).toHaveLength(16)
    })
})

describe("EncryptionProvider", () => {
    const resolve = (app: Record<string, unknown>) => {
        const container = new BuiltinContainer()
        container.instance("config", new ConfigRepository({ app }))
        new EncryptionProvider().register(container)
        return container
    }

    test("builds the encrypter from Laravel-style app config", async () => {
        const { key, payload } = laravel["aes-256-gcm"]
        const container = resolve({ key: laravel["aes-256-cbc"].key, cipher: "AES-256-GCM", previous_keys: [key] })
        const encrypter = container.make<Encrypter>("encrypter")

        expect(container.make(Encrypter)).toBe(encrypter)
        expect(encrypter.getKey()).toEqual(keyOf(laravel["aes-256-cbc"].key))
        expect(await encrypter.decryptString(payload)).toBe(PLAINTEXT)
    })

    test("defaults to aes-128-cbc and accepts a raw (non-base64) key", async () => {
        const encrypter = resolve({ key: "k".repeat(16) }).make<Encrypter>("encrypter")
        expect(await encrypter.decryptString(await encrypter.encryptString("x"))).toBe("x")
    })

    test("throws MissingAppKeyError without app.key", () => {
        expect(() => resolve({}).make("encrypter")).toThrow(MissingAppKeyError)
    })

    test("is deferred until the encrypter is resolved", () => {
        const provider = new EncryptionProvider()
        expect(provider).toBeInstanceOf(DeferrableServiceProvider)
        expect(provider.provides()).toEqual(["encrypter", Encrypter])
    })
})
